model:
  name: ibm-granite/granite-3.3-8b-instruct
vllm:
  provider_config: vllm_single_card
  overrides:
    kv_cache_memory: 0
    gpu_memory_utilization: 0.95
    port: 20502
    trust_remote_code: true
task_defaults:
  log_samples: true
  cuda_devices: '2'
tasks:
- latam_board
metadata:
  max_context_length: 131072
  supports_multimodal: false
  model_type: granite
  detected_from_config: true
  generated_at: '2025-10-15T16:55:01.224105'
  gpu_type: single
