model:
  name: Qwen/Qwen3-VL-4B-Instruct
vllm:
  provider_config: vllm_single_card_mm
  overrides:
    kv_cache_memory: 0
    gpu_memory_utilization: 0.95
    port: 20502
    trust_remote_code: true
    timeout: 240
task_defaults:
  log_samples: true
  cuda_devices: '2'
  batch_size: 10
tasks:
- latam_board
metadata:
  max_context_length: 8192
  supports_multimodal: true
  model_type: qwen3_vl
  detected_from_config: true
  generated_at: '2025-10-16T10:57:25.472415'
  gpu_type: single
